apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappservice
  template:
    metadata:
      labels:
        app: todoappservice
    spec:
      containers:
        - name: todoappcontainer
          image: todoappservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8093
          env:
            - name: db_oracle_userid
              value: DUMMY123
            - name: db_oracle_password
              value: system
            - name: db_oracle_schema
              value: DUMMY123