quarkus.openapi.generator.spec= products-openapi.yml
#quarkus.openapi.generator.input-base-dir=openapi-definitions
quarkus.openapi.generator.base-package=io.petstore
quarkus.openapi.generator.reactive=false
quarkus.smallrye-openapi.enabled=true
quarkus.smallrye-openapi.path=/swagger

quarkus.banner.enabled=false
quarkus.compose.devservices.enabled=false
quarkus.analytics.disabled=true
quarkus.http.port=8093
quarkus.application.name=openapi-with-quarkus
#quarkus.arc.dev-mode.monitoring-enabled=false