#genaral settings for quarkus
quarkus.banner.enabled= false
quarkus.application.name=employee-service
quarkus.application.version=1.0-SNAPSHOT


#Logger config
quarkus.log.level=INFO

quarkus.log.console.level = INFO
quarkus.log.console.enabled= true
quarkus.log.console.format= %d{yyyy-MM-dd HH:mm:ss}  %c %p [%t]: %m %n

quarkus.log.file.enable=false

#profile specific property
quarkus.profile=dev
%prod.employee.department=IT
%dev.employee.department=Testing

#docker
quarkus.container-image.build=true
quarkus.container-image.labels=quarkusdemo
quarkus.container-image.name=${quarkus.application.name:unset}
quarkus.container-image.tag=${quarkus.application.version:latest}


