quarkus.azure-functions.app-name=azure-func-trigger
quarkus.analytics.disabled=true
quarkus.application.name=azure-func-trigger
quarkus.azure-functions.runtime.java-version=17
quarkus.azure-functions.runtime.os=windows
quarkus.azure-functions.func-port=8093
quarkus.azure-functions.disable-app-insights=true