--DELETE FROM CATEGORY ;
--DELETE FROM PRODUCT ;
--DELETE FROM USER ;
--DELETE FROM ROLE ;
--DROP TABLE IF EXISTS USER_ROLE ;
--CREATE TABLE USER_ROLE(
-- USER_ID integer not null ,
-- ROLE_ID integer not null ,
-- PRIMARY KEY(USER_ID , ROLE_ID) ,
-- FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ,
-- FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE SET NULL ON UPDATE CASCADE
-- );

INSERT INTO category (category_id,category_name) VALUES (1 ,'Fashion');
INSERT INTO category (category_id,category_name) VALUES (2 , 'Electronics');
INSERT INTO category (category_id,category_name) VALUES (3 , 'Books');
INSERT INTO category (category_id,category_name) VALUES (4 , 'Groceries');
INSERT INTO category (category_id,category_name) VALUES (5 , 'Medicines');

INSERT INTO USER(USER_NAME , USER_PASSWORD) VALUES('jack' , 'pass_word');
INSERT INTO USER(USER_NAME , USER_PASSWORD) VALUES('bob' , 'pass_word');
INSERT INTO USER(USER_NAME , USER_PASSWORD) VALUES('apple' , 'pass_word');
INSERT INTO USER(USER_NAME , USER_PASSWORD) VALUES ('glaxo' , 'pass_word');



INSERT INTO ROLE(ROLE) VALUES ('CONSUMER') ;
INSERT INTO ROLE(ROLE) VALUES ('SELLER') ;

INSERT INTO USER_ROLE VALUES(1,1) ;
INSERT INTO USER_ROLE VALUES(2,1) ;
INSERT INTO USER_ROLE VALUES(3,2) ;
INSERT INTO USER_ROLE VALUES(4,2) ;

INSERT INTO PRODUCT(PRODUCT_NAME  , CATEGORY_ID , SELLER_ID , PRICE) VALUES ('Apple Ipad 10.2' , 2 , 3 , 29190) ;
INSERT INTO PRODUCT(PRODUCT_NAME  , CATEGORY_ID , SELLER_ID , PRICE) VALUES ('Crocin Tablet' , 5 , 4 , 10) ;

INSERT INTO CART (TOTAL_AMOUNT , USER_ID) VALUES (20 , 1) ;
INSERT INTO CART (TOTAL_AMOUNT , USER_ID) VALUES (0 , 2) ;

INSERT INTO CART_PRODUCT(CART_ID , PRODUCT_ID , QUANTITY) VALUES(1,2,2) ;



