mongo_db.local.url:blank
mongo_db.atlas.url:mongodb+srv://$1:$2
mongo_db.atlas.cluster:@cluster-practice.infjppq.mongodb.net/?retryWrites=true&w=majority&appName=
mongo_db.atlas.cluster_name:Cluster-Practice