mongo_db.local.url:blank
mongo_db.atlas.url_protocol:mongodb+srv://
mongo_db.atlas.creds=$1:$2
mongo_db.atlas.cluster_url:@cluster-practice.infjppq.mongodb.net/?retryWrites=true&w=majority&appName=
mongo_db.atlas.cluster_name:Cluster-Practice
mongo_db.atlas.db_name: sample_mflix