status = warn
name= LinkedInMongoAtlasDBLogger
# Log files location
property.basePath = logs/

appenders = console,FILE_LOGGER,MONGO_LOGGER,EXCEPTION_LOGGER
# Change the package structure as per your application

# Console appender
appender.console.type= Console
appender.console.name=CONSOLE_LOGGER
appender.console.layout.type=PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p [%l] %c - %m%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = info

# RollingFileAppender for general logs
appender.FILE_LOGGER.type = RollingFile
appender.FILE_LOGGER.name = FILE_LOGGER
appender.FILE_LOGGER.fileName= ${basePath}/app.log
appender.FILE_LOGGER.filePattern= ${basePath}/app_%d{yyyy-MM-dd}-%i.log.gz
appender.FILE_LOGGER.layout.type = PatternLayout
appender.FILE_LOGGER.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%l] - %msg%n
appender.FILE_LOGGER.policies.type = Policies

# Define the threshold for FILE_LOGGER
appender.FILE_LOGGER.filter.threshold.type = ThresholdFilter
appender.FILE_LOGGER.filter.threshold.level = debug

# RollingFileAppender rotation policy for FILE_LOGGER
appender.FILE_LOGGER.policies.size.type = SizeBasedTriggeringPolicy
appender.FILE_LOGGER.policies.size.size = 10MB
appender.FILE_LOGGER.policies.time.type = TimeBasedTriggeringPolicy
appender.FILE_LOGGER.policies.time.interval = 1
appender.FILE_LOGGER.policies.time.modulate = true
appender.FILE_LOGGER.strategy.type = DefaultRolloverStrategy
appender.FILE_LOGGER.strategy.delete.type = Delete
appender.FILE_LOGGER.strategy.delete.basePath = ${basePath}
appender.FILE_LOGGER.strategy.delete.maxDepth = 10
appender.FILE_LOGGER.strategy.delete.ifLastModified.type = IfLastModified
# Delete all files older than 30 days
appender.FILE_LOGGER.strategy.delete.ifLastModified.age = 30d

# RollingFileAppender for MongoDB logs
appender.MONGO_LOGGER.type = RollingFile
appender.MONGO_LOGGER.name = MONGO_LOGGER
appender.MONGO_LOGGER.fileName= ${basePath}/cluster.log
appender.MONGO_LOGGER.filePattern= ${basePath}/cluster_%d{yyyy-MM-dd}-%i.log.gz
appender.MONGO_LOGGER.layout.type = PatternLayout
appender.MONGO_LOGGER.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%l] - %msg%n
appender.MONGO_LOGGER.policies.type = Policies

# Define the threshold for MONGO_LOGGER
appender.MONGO_LOGGER.filter.threshold.type = ThresholdFilter
appender.MONGO_LOGGER.filter.threshold.level = info

# RollingFileAppender rotation policy for MONGO_LOGGER
appender.MONGO_LOGGER.policies.size.type = SizeBasedTriggeringPolicy
appender.MONGO_LOGGER.policies.size.size = 10MB
appender.MONGO_LOGGER.policies.time.type = TimeBasedTriggeringPolicy
appender.MONGO_LOGGER.policies.time.interval = 1
appender.MONGO_LOGGER.policies.time.modulate = true
appender.MONGO_LOGGER.strategy.type = DefaultRolloverStrategy
appender.MONGO_LOGGER.strategy.delete.type = Delete
appender.MONGO_LOGGER.strategy.delete.basePath = ${basePath}
appender.MONGO_LOGGER.strategy.delete.maxDepth = 10
appender.MONGO_LOGGER.strategy.delete.ifLastModified.type = IfLastModified
# Delete all files older than 5 days
appender.MONGO_LOGGER.strategy.delete.ifLastModified.age = 5d

# RollingFileAppender for Exception logs
appender.EXCEPTION_LOGGER.type = RollingFile
appender.EXCEPTION_LOGGER.name = EXCEPTION_LOGGER
appender.EXCEPTION_LOGGER.fileName= ${basePath}/errors.log
appender.EXCEPTION_LOGGER.filePattern= ${basePath}/cluster_%d{yyyy-MM-dd}-%i.log.gz
appender.EXCEPTION_LOGGER.layout.type = PatternLayout
appender.EXCEPTION_LOGGER.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%l] - %msg%n
appender.EXCEPTION_LOGGER.policies.type = Policies

# Define the threshold for EXCEPTION_LOGGER
appender.EXCEPTION_LOGGER.filter.threshold.type = ThresholdFilter
appender.EXCEPTION_LOGGER.filter.threshold.level = error

# RollingFileAppender rotation policy for EXCEPTION_LOGGER
appender.EXCEPTION_LOGGER.policies.size.type = SizeBasedTriggeringPolicy
appender.EXCEPTION_LOGGER.policies.size.size = 10MB
appender.EXCEPTION_LOGGER.policies.time.type = TimeBasedTriggeringPolicy
appender.EXCEPTION_LOGGER.policies.time.interval = 1
appender.EXCEPTION_LOGGER.policies.time.modulate = true
appender.EXCEPTION_LOGGER.strategy.type = DefaultRolloverStrategy
appender.EXCEPTION_LOGGER.strategy.delete.type = Delete
appender.EXCEPTION_LOGGER.strategy.delete.basePath = ${basePath}
appender.EXCEPTION_LOGGER.strategy.delete.maxDepth = 10
appender.EXCEPTION_LOGGER.strategy.delete.ifLastModified.type = IfLastModified
# Delete all files older than 50 days
appender.EXCEPTION_LOGGER.strategy.delete.ifLastModified.age = 50d

loggers =  infoLogger , daoLogger,pipelinesLogger,mongoClusterLogger , exceptionLogger
# Configure package
logger.daoLogger.name = com.demo.dao
logger.daoLogger.level = debug
logger.daoLogger.additivity = false
logger.daoLogger.appenderRef.rolling.ref = FILE_LOGGER

logger.pipelinesLogger.name = com.demo.pipelines
logger.pipelinesLogger.level = debug
logger.pipelinesLogger.additivity = false
logger.pipelinesLogger.appenderRef.rolling.ref = FILE_LOGGER

logger.mongoClusterLogger.name = org.mongodb
logger.mongoClusterLogger.level = info
logger.mongoClusterLogger.additivity = false
logger.mongoClusterLogger.appenderRef.rolling.ref = MONGO_LOGGER

logger.infoLogger.name = com.demo
logger.infoLogger.level = info
logger.infoLogger.additivity = false
logger.infoLogger.appenderRef.console.ref = CONSOLE_LOGGER
logger.infoLogger.appenderRef.rolling.ref = FILE_LOGGER

logger.exceptionLogger.name = AppException
logger.exceptionLogger.level = error
logger.exceptionLogger.additivity = false
logger.exceptionLogger.appenderRef.rolling.ref = EXCEPTION_LOGGER

# Configure root logger
rootLogger.level = info
rootLogger.appenderRef.console.ref = CONSOLE_LOGGER
rootLogger.appenderRef.rolling.ref = FILE_LOGGER