logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.file.debug=debug.log
logging.file.error=error.log

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.com.example=ERROR