local.servicebus.connection.string=Endpoint=sb://127.0.0.1:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=DUMMY_KEY_FOR_EMULATOR;UseDevelopmentEmulator=true;
local.servicebus.queue.name=queue.1
local.servicebus.topic.name=topic.1
local.servicebus.subscribers=subscription.1, subscription.simple